Poetry
icecube/flarestack pull request #200
Opened 2022-09-19 14:21 UTC by JannisNe

We should use [`poetry`](https://python-poetry.org) to do the installation. Brings the advantage of built-in environment resolving and a full lock file that documents every single package version. Also, dependencies can be specified in a range, e.g. `~3.2.1` allows everything from `3.2.1` to `<4.0.0`
This makes `setup.py` and `requrements.txt` obsolete and add `pyproject.toml` and `poetry.lock`.
I updated installation when building docs and the CI.

2022-09-19 17:15 UTC, robertdstein commented on pyproject.toml
> +    "Robert Stein <robert.stein@desy.de>",
I'd update my email: rdstein@caltech.edu

2022-09-19 17:15 UTC, robertdstein commented on pyproject.toml
> +authors = ["Robert Stein <robert.stein@desy.de>"]
Update email: rdstein@caltech.edu

2022-09-19 17:16 UTC, robertdstein commented on docs/source/setup.md
> +A less flexible option is to use *pip*
I'd be a bit more neutral:

'Another option is to use *pip*:'

2022-09-19 17:16 UTC, robertdstein requested changes
I like this a lot. My only suggested change is to update my email to the present one.

2022-09-19 17:24 UTC, JannisNe commented
Implemented the changes

2022-09-19 17:31 UTC, robertdstein approved these changes

2022-09-19 17:34 UTC, JannisNe commented on pyproject.toml
> +    "Robert Stein <robert.stein@desy.de>",
done

2022-09-20 14:16 UTC, mlincett commented
This is very nice. Could you update the documentation to cover the case of  _"OPTION B: Actually, I want to see the backend code myself. Maybe I want to contribute to it!"_ ?

Also let's not forget to keep the main `README` file aligned.

2022-09-22 08:32 UTC, JannisNe commented
Done. Is that good to merge now you think, @mlincett ?

2022-09-22 14:02 UTC, mlincett approved these changes
Thank you, looks good.

2022-09-22 14:05 UTC, merged