Cluster submission fixes
icecube/flarestack pull request #213
Opened 2022-10-07 16:15 UTC by mlincett

Try to fix #181 following @robertdstein suggestion of using `sys.executable` as python command for running in the DESY cluster.

Adding a also deprecation warning to legacy `make_desy_cluster_script` module.

2022-10-10 10:56 UTC, JannisNe approved these changes

2022-10-10 18:35 UTC, robertdstein requested changes

2022-10-10 18:35 UTC, robertdstein commented on flarestack/cluster/submitter.py
> +            f"{sys.executable} "
I think the f string thing looks messy here. I think the following is cleaner and should pass black:

```
f"{sys.executable} {fs_dir} core/multiprocess_wrapper.py -f $1 -n $2 \n"
```

2022-10-13 19:26 UTC, robertdstein approved these changes

2022-10-14 08:59 UTC, merged