Band masks fix
icecube/flarestack pull request #307
Opened 2023-09-11 19:33 UTC by sathanas31

**Major change**: 
Tackle #7 with `make_band_masks_wrapper` for making band masks when minimizer is `large_catalogue` and band masks are not already written. Currently its module `make_band_mask` is called in the submitter's `submit` method to run 1 trial locally, but in principle the wrapper can be run as a stand alone in case we decide to switch to dagmans

2023-09-11 20:16 UTC, mlincett requested changes

2023-09-11 20:16 UTC, mlincett commented on flarestack/data/icecube/ic_season.py
Could you explain what issue is this trying to solve? I think this used to work on the DESY cluster.

2023-09-11 20:16 UTC, mlincett commented on flarestack/data/icecube/ic_season.py
> +        ref_10yr = WIPAC_10yr_dir / ref_10yr_filename
This is now lacking a default definition for when `flarestack` is not running either at DESY or WIPAC.

2023-09-12 08:12 UTC, sathanas31 commented on flarestack/data/icecube/ic_season.py
Actually no it didn't, the reference sensitivities are under `/ref_sensitivity` at DESY mirror which was not reflected in the path, hence the warnings in the logs

2023-09-12 08:57 UTC, mlincett commented on flarestack/data/icecube/ic_season.py
In the [current `master`](https://github.com/icecube/flarestack/blob/master/flarestack/data/icecube/ic_season.py) if:
- `FLARESTACK_DATASET_DIR` is not set;
- `host_server` is `"DESY"`;
data and sensitivities should be loaded from the hardcoded DESY paths defined as:
https://github.com/icecube/flarestack/blob/30b9725fce2be5d898d3d9896627f335477cfdf8/flarestack/data/icecube/ic_season.py#L72-L73

Do you maybe have `FLARESTACK_DATASET_DIR` pointing to the DESY mirror directory? In that case, `flarestack` will try to use it as if it was a "local" mirror, hence the different path structure.

2023-09-12 09:04 UTC, JannisNe commented on flarestack/core/make_band_masks_wrapper.py
Just my taste, but I think a more natural place for this is a method of `Submitter` or in `utils.py`

2023-09-12 09:06 UTC, mlincett commented on flarestack/data/icecube/ic_season.py
We can agree on a design where we expect "local" mirror to follow the same directory structure we have at DESY (which is not bad per se). So conceptually the code would look like:
```
if not_on_WIPAC:
    data_dir = FLARESTACK_DATASET_DIR or DESY_MIRROR_DIR
    sens_dir = FLARESTACK_DATASET_DIR/ref_sensitivity
```
with maybe some check whether we are actually on DESY before trying to read from `DESY_MIRROR_DIR`.

2023-09-12 09:08 UTC, JannisNe commented
Also, please keep the CI happy and format according to (or autoformat by) [black](https://black.readthedocs.io/en/stable/).

2023-09-12 10:03 UTC, sathanas31 commented on flarestack/core/make_band_masks_wrapper.py
put it in the `utils.py` since I don't want to pollute `Submitter`, is that ok?

2023-09-12 11:31 UTC, sathanas31 commented on flarestack/data/icecube/ic_season.py
Currently `FLARESTACK_DATASET_DIR` is not set so it goes into [L76](https://github.com/icecube/flarestack/blob/30b9725fce2be5d898d3d9896627f335477cfdf8/flarestack/data/icecube/ic_season.py#L76) which is fine.
Apparently, before making the changes, it was set incorrectly when I ran some test scripts, never set it manually so I can't really say how this happened, hence pointing to the wrong path (ie `/lustre/fs22/group/icecube/data_mirror`) which gave me the warnings (eg "No 10yr sensitivity found")
I'll revert back to the previous version since I think it's more robust

2023-09-20 15:00 UTC, mlincett approved these changes

2023-09-21 14:50 UTC, mlincett commented
@dependabot rebase

2023-09-24 18:02 UTC, merged